### ISSUE TITLE
access django request in OAuth2Validator.get_additional_claims

### ISSUE THREAD

**Issue by amirhoseinbidar** [jazzband/django-oauth-toolkit#1018]
In get_additional_claims I want to give url of users avatar, some thing like google claims...
But django image field just give path of file without domain
base on https://stackoverflow.com/questions/1451138/how-can-i-get-the-domain-name-of-my-site-within-a-django-template
I have to somehow access django request to find site domain and build avatars full url

But base on https://django-oauth-toolkit.readthedocs.io/en/1.5.0/oidc.html?highlight=OAuth2Validator#adding-claims-to-the-id-token
request object that pass to get_additional_claims isn't a django request object and seems have no data of site domin and its schema to build full url

I know i can set a variable in setting like `SITE_URL` or use `contrib.site` to build full url and currently use `SITE_URL` but using django request objest is far better solution because won't break when domain changed

So is there any way to access django request object or can you provide a interface( or anything ) for it?

**Comment by dopry** [comment]
This change to the request happens upstream in [OAuthLib.common.Request]( https://github.com/oauthlib/oauthlib/blob/eddb461c1043f8ad583fd67af34749e32fdc19cc/oauthlib/common.py#L331) 

We have no control over it in DOT. If you can't get the domain from their implementation it won't be available in DOT.  I would lean on settings to ensure you're using a Canonical URL rather than the request url which can get weird if you have CDNs or other proxies in the middle or you serve images off a 3rd part platform like S3.
