### ISSUE TITLE
Resolve issues with Django >= 4.0

### ISSUE THREAD

**Issue by n2ygk** [jazzband/django-oauth-toolkit#1051]
**Describe the bug**

See #1039 issues with migrations. Keeping this issue open in order to remind us.

**To Reproduce**

**Expected behavior**

**Version**

- [ ] I have tested with the latest published release and it's still a problem.
- [ ] I have tested with the master branch and it's still a problem.

**Additional context**

**Comment by Andrew-Chen-Wang** [comment]
Should this be resolved when https://github.com/django/django/pull/15205 is released or are you saying to try and support 4.0.0? Or are you saying resolve Django main branch issues? Sorry for the confusion 😅

**Comment by n2ygk** [comment]
> Should this be resolved when [django/django#15205](https://github.com/django/django/pull/15205) is released or are you saying to try and support 4.0.0? Or are you saying resolve Django main branch issues? Sorry for the confusion 😅

I just don't want to let the problem with 4.0 drop, so either we document the issue so users don't get burned by it or wait to see if 4.0.1 fixes it. It would be nice to have a failing test somehow to confirm that the migration breakage is in fact resolved and doesn't come back as another regression.

**Comment by n2ygk** [comment]
@Andrew-Chen-Wang I admit that TL;DR on the reasons for DOT having issues with DJ4.0. Do you agree we should drop 4.0 support from the 1.6.x release until that regression is fixed and 4.0.1 is published? We can target that for 1.7.0.

**Comment by Andrew-Chen-Wang** [comment]
> It would be nice to have a failing test somehow to confirm that the migration breakage is in fact resolved and doesn't come back as another regression.

We can add a test case that runs `assert call_command("makemigrations", "--check")` so that no new migrations pops up.

> wait to see if 4.0.1 fixes it

The PR has merged and is documented in 4.0.1 release notes (though the version has not been released yet; expected release on January 4th, 2022): https://docs.djangoproject.com/en/4.0/releases/4.0.1/

> Do you agree we should drop 4.0 support from the 1.6.x release until that regression is fixed and 4.0.1 is published? We can target that for 1.7.0.

I think that, given the patch release of 4.0.1 is coming out in two weeks, we should be fine to leave the current requirements settings as is. I don't think it makes sense for us to release django-oauth-toolkit 1.6.2 to drop 4.0 Django *now* only for 1.7.0 to add back 4.0 support in just two weeks. I will update you in this GH issue if, for some reason, the patch was not updated in 4.0.1 or something else from 4.0 breaks something.

I do agree that we should document the issue somewhere in the docs (for SEO and RTD search engine purposes) and README (for confused users to immediately read why 4.0.0 doesn't work). I believe the CHANGELOG is already included in the docs, so I will modify the CHANGELOG to include an explanation for why 4.0.0 wasn't included. I will update the README to give the same explanation.
