### ISSUE TITLE
Why Authorization grant type is Authorization code still need with header "Authorization: Basic ${CREDENTIAL}"

### ISSUE THREAD

**Issue by leench** [jazzband/django-oauth-toolkit#1180]
I tested django-oauth-toolkit 2.1.0, the **Authorization grant type** is **Authorization code**. and I found out that I have to pass **Authorization header** to get token successfully.
This is a successful request:

<img width="782" alt="1" src="https://user-images.githubusercontent.com/157350/175804023-6137e771-49d5-4f80-abc0-107b5d51556f.png">

If don't, will return error with "invalid_client"

**Comment by n2ygk** [comment]
Yes, that's how OAuth2 works.

The client (what DOT calls application) authenticates to the Authorization Server with Basic Auth which is a base64-encoded(client_id:client_secret).  Then the AS makes things happen (e.g. redirects the user's browser to a login service) and eventually returns an Access Token to the client which it can use as a Bearer token in an Authorization header sent to a Resource Server.

See https://datatracker.ietf.org/doc/html/rfc6749#section-2.3

"invalid_client" is returned for many reasons:
- because you didn't identify on (e.g. with a basic auth header)
- because you used an incorrect or missing client_id in the basic auth header
- because you used an incorrect client_secret in the basic auth header.

**Comment by leench** [comment]
Thx a lot!
