### ISSUE TITLE
Use JWT as token format instead of Bearer (opaque)

### ISSUE THREAD

**Issue by kiraware** [jazzband/django-oauth-toolkit#1242]
Hi there! I would like to know if there is a way to get OAuth2 Provider use JWT token instead of Bearer token for it's access token and refresh token? I think it would be nice if django-oauth-toolkit has support on this. Thanks!

**Comment by kiraware** [comment]
Based on openid connect documentation at https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse, it stated that

> The OAuth 2.0 `token_type` response parameter value MUST be `Bearer`, as specified in [OAuth 2.0 Bearer Token Usage](https://openid.net/specs/openid-connect-core-1_0.html#RFC6750) [RFC6750], unless another Token Type has been negotiated with the Client. Servers SHOULD support the `Bearer` Token Type; use of other Token Types is outside the scope of this specification.

Based on this documentation, it looks like the `token_type` MUST be `Bearer`, but it also allow the other token type if the client request it, e.g. request JWT instead. I think support of this is a good idea. Any thought of you?

**Comment by JordiNeil** [comment]
Hi, as far as I know, JWT should not be used for API calls, because as they're self-contained, there's no easy way to expire them. They'll always work until its expiration time. You can read more about it [here](https://auth0.com/blog/id-token-access-token-what-is-the-difference/#:~:text=One%20of%20the%20most%20common%20mistakes%20developers%20make%20with%20an%20ID%20token%20is%20using%20it%20to%20call%20an%20API)

JWT should be used to send information to a client o another server in a secure way because it is signed, then you can verify the identity of who generated that information.

**Comment by kiraware** [comment]
Thanks for your response @JordiNeil. I close my comment. Im agree with your opinion
