### ISSUE TITLE
Minor/patch release cycle with bugfixes

### ISSUE THREAD

**Issue by cristiprg** [jazzband/django-oauth-toolkit#1478]
Hi! Do you have any plans to release another minor or patch version before the major upgrade to 3? There are a couple of smaller non-breaking fixes that would be great to have in, such as https://github.com/jazzband/django-oauth-toolkit/pull/1476 and  https://github.com/jazzband/django-oauth-toolkit/pull/1465 which fixes [this CVE](https://github.com/advisories/GHSA-3pgj-pg6c-r5p7). 🙏

**Comment by n2ygk** [comment]
I've pushed the date earlier and hope to publish the 3.0.0 version before then. I'm waiting on one or two last PR reviews. See https://github.com/jazzband/django-oauth-toolkit/milestone/35.  It seems that oauthlib [CVE](https://github.com/advisories/GHSA-3pgj-pg6c-r5p7) can be dealt with now by upgrading oauthlib as the DOT 2.4.0 requirements are for `oauthlib 3.1+` so 3.2.2+ is included in that. Given the dependency should be `>=3.2.2` rather than `>=3.2` as it was in #1465 it would be great if you were to submit a PR to push the version dependency to that level.

**Comment by cristiprg** [comment]
Thanks @n2ygk! Here's the PR to bump oauthlib https://github.com/jazzband/django-oauth-toolkit/pull/1481

**Comment by cristiprg** [comment]
@n2ygk sorry, I may have not asked the question clearly. What I'm interested is having those two PRs _before_ a major release with breaking changes, in for example DOT 2.4.1 or 2.5. 

The motivation is that they are not breaking changes, so there is no need to only include them in a major release

**Comment by n2ygk** [comment]
That’s too much effort for me to have to create a branch and cherry pick
intermediate commits.
