### ISSUE TITLE
After getting this library upgrade token index removed

### ISSUE THREAD

**Issue by vipulprajapatiLTIM** [jazzband/django-oauth-toolkit#1520]
**Describe the bug**
token index is being removed when we upgraded this library to 3.0.1

**To Reproduce**
Upgrade library to 3.0.1 and apply migrations it will remove index on token column in access_token table.

**Expected behavior**
Index should not have been dropped.

**Version**
3.0.1

 yes

- [ x] I have tested with the latest published release and it's still a problem.
- [ x] I have tested with the master branch and it's still a problem.

**Additional context**
Got DB error while doing migrations
![image](https://github.com/user-attachments/assets/fe6f8c83-9c92-46c1-8806-e3686c0c6ff2)

**Comment by vipulprajapatiLTIM** [comment]
main issue is here in this migration
https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/migrations/0012_add_token_checksum.py

token column datatype is changed so index is being dropped

**Comment by n2ygk** [comment]
That's because the update uses the token_checksum for the search for matching token. You can't index a long text column in many dstabase engines.

Do you now see an index on token_checksum? It's added here: 

https://github.com/jazzband/django-oauth-toolkit/blob/1c5e36d59cd8f740650a72ad80a455f8ed05ff3c/oauth2_provider/migrations/0012_add_token_checksum.py#L35

**Comment by vipulprajapatiLTIM** [comment]
Got it. Thanks for clarification
