### ISSUE TITLE
Authorization Server

### ISSUE THREAD

**Issue by chrux** [jazzband/django-oauth-toolkit#500]
Hi,

Is there a way to make an authorization server which take into account the application and a group if the group does not have permission to access the application, we should not allow further access, neither provide a token, Is that possible?

Best

**Comment by menecio** [comment]
Hey, please post questions on the google group https://groups.google.com/forum/#!forum/django-oauth-toolkit

**Comment by jleclanche** [comment]
Honestly this is fine too.

**Comment by Colleoni** [comment]
Hi I have the same question, 

I want to deploy two applications on the same server as the API are the same, but I want to restrict users to access to a single app. So that users of the first app could not access the second app and viceversa. Is that possible in DOT?

Thanks 

PS: The link in the first answer does not work, it says that there is no group named "django-oauth-toolkit" in google groups.

**Comment by andjimrio** [comment]
RT
