### ISSUE TITLE
Skip authorization does not prevent redirect to authorization page

### ISSUE THREAD

**Issue by HawiCaesar** [jazzband/django-oauth-toolkit#581]
Good day, 

I was trying to implement the [skip authorization](https://django-oauth-toolkit.readthedocs.io/en/latest/advanced_topics.html#skip-authorization-completely-for-trusted-applications) feature but I ran into a hurdle while testing it out on postman. 
Check out the screenshot
<img width="1440" alt="screen shot 2018-04-10 at 17 00 23" src="https://user-images.githubusercontent.com/6042152/38561436-b7052a1c-3ce0-11e8-95f4-240499281e29.png">
Sending a request via postman is redirecting me to the `/accounts/login...` of which I am trying skip.
This is the terminal response. 
```terminal
[10/Apr/2018 14:01:28] "GET /o/authorize/?client_id=4TUHT8bGgJ4Pl2UBVu7GLTHyuBohC8zpFUkkXRrN&scope=&state=11647116&redirect_uri=https%3A%2F%2Fwww.getpostman.com%2Foauth2%2Fcallback&response_type=code HTTP/1.1" 302 0
Not Found: /accounts/login/
[10/Apr/2018 14:01:28] "GET /accounts/login/?next=/o/authorize/%3Fclient_id%3D4TUHT8bGgJ4Pl2UBVu7GLTHyuBohC8zpFUkkXRrN%26scope%3D%26state%3D11647116%26redirect_uri%3Dhttps%253A%252F%252Fwww.getpostman.com%252Foauth2%252Fcallback%26response_type%3Dcode HTTP/1.1" 404 12484
```
I followed [this](http://django-oauth-toolkit.readthedocs.io/en/latest/install.html) and [this](http://django-oauth-toolkit.readthedocs.io/en/latest/rest-framework/getting_started.html#step-1-minimal-setup) when setting up the oauth toolkit

What could I be doing wrong ?

**Comment by jdelic** [comment]
`skip_authorization` on the Application model does not _skip_ the `AuthorizationView` it only skips the HTML form display and immediately sends the user on their way. This is necessary, as the application still has to be "authorized" in the database (the tokens have to be created etc.), the user just doesn't get to agree.

@ohcibi It's set on the `Application` database model, for example as a checkbox in the Django Admin interface.

**Comment by ohcibi** [comment]
@jdelic that clearly needs some more documentation. I'm planning to build an api-only app with django and I won't be using any of the the generated html views from django. The documentation is way to centric on using the pre generated views. I simply want to login with credentials and receive the access token as a response in the client to authorize further requests with. The app is trusted so the request should not be redirected but simply receive the access token as the response.

If you say its set on the Application database model as a checkbox in the admin interface, I guess you are actually referring to a database record which gets (like the way the orm system of django works) represented by an instance of the application model class which should have a field `skip_authorization`, right? Does that mean I have to preseed the database with an application record with that field set to true for a trusted application? Do I even need to extend the application model for it or is that field actually already present in the base class?

**Comment by jdelic** [comment]
@ohcibi 
> I simply want to login with credentials and receive the access token as a response in the client to authorize further requests with.

That shouldn't be a problem. The main question is _where do you want the user to enter the credentials_? As I see it you can use either the Client Authorization OAuth2 flow or the Resource Owner OAuth2 flow , depending on whether the user should be redirected to a login screen on the OAuth2 server or whether he should enter his credentials directly into the client. The Client Authorization flow is obviously more secure, whereas the Resource Owner flow is literally "post username/password to /token/ and receive the access token in response". `skip_authorization` is that you want for "client_ids" (Applications) that you trust. 

> Do I even need to extend the application model for it or is that field actually already present in the base class?

The [default Application model](https://github.com/jazzband/django-oauth-toolkit/blob/b4378b3d3197c4fb7b13b0f7ba624616f4241f28/oauth2_provider/models.py#L78) has `skip_authorization` built in. But you can replace the Application model with your own (it's `swappable` which is currently an undocumented internal API in Django). An example for how to use your own Application model can be found [on my `authserver` project](https://github.com/jdelic/authserver/blob/561c245b8680f546a310109b312532939a703dab/authserver/mailauth/models.py#L371) (also see `authserver.settings` and the associated initial migration on `mailauth`).

> Does that mean I have to preseed the database with an application record with that field set to true for a trusted application?

Yes, you have to create entries for your clients _and_ distribute their secrets to the clients. I build infrastructure in `authserver` to do this in the form of [custom management commands](https://github.com/jdelic/authserver/blob/561c245b8680f546a310109b312532939a703dab/authserver/mailauth/management/commands/oauth2.py#L37) which allow you to create applications from a script on the OAuth2 server and then publish the client secret to [Hashicorp Vault](https://vaultproject.io) (or Consul), where clients can then retrieve their secret from using `consul-template` or direct API access. Obviously nothing keeps you from just copy/pasting the secret :).

**Comment by jdelic** [comment]
@ohcibi 
Reading over my previous response... let me be more precise

> I'm planning to build an api-only app with django and I won't be using any of the the generated html views from django. The documentation is way to centric on using the pre generated views.

I think that's primarily because OAuth2 is centered around the Client Authorization flow that requires the user to be sent to a HTML login form and then redirected back to the client application. If you want to use OAuth2 just to authenticate the user and authorize an application the [Resource Owner flow is your thing (link to spec)](https://tools.ietf.org/html/rfc6749#section-4.3).

> The app is trusted so the request should not be redirected but simply receive the access token as the response.

If you're talking about a _single client_ for your API (i.e. "the app" here is singular), then ignore everything I wrote above about the "secret introduction problem", because you can just create a client secret for your app (or perhaps better design: separate client secrets for every release version of your app) and ship it with the app.

Only if "the app" is a single-page JavaScript application you might want to look at the Implicit OAuth2 flow... which _does require a login page redirect_, which you said you don't want to use, but is optimized to handle clients that can't reasonably keep secrets.

**Comment by ohcibi** [comment]
@jdelic Yes the resource owner flow is what I was going for. I implemented it in my client by just passing the data described in the rfc. However when I tried that with the django-oauth-toolkit enabled backend I got that redirect. I'm missing the point where I can tell the toolkit to follow the resource owner flow instead of the client authorization flow or what and how I need to pass my data to trigger that flow?

**Comment by emoragaf** [comment]
@ohcibi you can set the flow when on the DOT application creation

**Comment by ohcibi** [comment]
@emoragaf could you elaborate your response a bit? As I said that 'application creation' is one of the things that causes the most confusion here 8-).

The simple thing I want to solve is to follow the resource owner flow as described in the RFC which *does not* involve any kind of redirect to another login page but simply responds the access token when the user POSTs the right credentials.

**Comment by jdelic** [comment]
@ohcibi
> could you elaborate your response a bit? As I said that 'application creation' is one of the things that causes the most confusion here 8-).

He means: 
  * when you create a `oauth2_provider.models.Application` instance (which will save a Django model in your application's database)
  * you set `my_application.authorization_grant_type = Application.GRANT_PASSWORD` (see [relevant](https://github.com/jazzband/django-oauth-toolkit/blob/b4378b3d3197c4fb7b13b0f7ba624616f4241f28/oauth2_provider/models.py#L47) [source code](https://github.com/jazzband/django-oauth-toolkit/blob/b4378b3d3197c4fb7b13b0f7ba624616f4241f28/oauth2_provider/models.py#L47))

which marks this `Application` instance as using the Resource Owner Password Credentials flow. It's even easier when you use Django's Admin interface to create the Application. Just choose "Resource owner password-based" from the dropdown for the "Authorization grant type" field. Basically you run something like this:

```python
>>> from oauth2_provider.models import Application
>>> Application.objects.create(authorization_grant_type=Application.GRANT_PASSWORD, client_type=Application.CLIENT_PUBLIC)
```

**Notes for your implementation:**

With a single-page application you probably also want to set `my_application.client_type = Application.CLIENT_PUBLIC`, because the `client_secret` would be easily stolen. Regardless, you'll have to send at least the `client_id` of your `Application` instance in the `Authorization` HTTP header (or inside the POST body) as described in [OAuth2 Section 2.3 (link to spec)](https://tools.ietf.org/html/rfc6749#section-2.3).

You then hook up the `TokenView` included in django-oauth-toolkit in your Django server application as described in the docs ([here is an example from my authserver application](https://github.com/jdelic/authserver/blob/561c245b8680f546a310109b312532939a703dab/authserver/authserver/urls.py#L29)) and follow [OAuth2 Section 4.3.2 (link to spec)](https://tools.ietf.org/html/rfc6749#section-4.3.2). The tl;dr here is: Send `grant_type=password&username=[username]&password=[password]` via `POST` to your `TokenView` URL. Assuming that a `django.contrib.auth.models.User` (or something similar that the Django auth framework can authenticate) exists with username `[username]` and password `[password]`, django-oauth-toolkit should create an access token in your database and reply with it.

Does this make things more clear?
