### ISSUE TITLE
After i swap the application model access_token fail

### ISSUE THREAD

**Issue by tximpa91** [jazzband/django-oauth-toolkit#605]
I am using the last version of the package the error that is giving me is 

('INSERT INTO "oauth2_provider_accesstoken" ("user_id", '  '"source_refresh_token_id", "token", "application_id", "expires", "scope", '  '"created", "updated") VALUES (%s, %s, %s, %s, %s, %s, %s, %s) RETURNING '  '"oauth2_provider_accesstoken"."id"')
 
and of course source_refresh_token_id doesnt exists in the access_token table

**Comment by jdelic** [comment]
@tximpa91 
`source_refresh_token` is created in [migrations/0006_auto_20171214_2232.py](https://github.com/jazzband/django-oauth-toolkit/blob/86e8f9b22c9d5957b8ff6097208de69758a3c013/oauth2_provider/migrations/0006_auto_20171214_2232.py#L17) in the latest stable release (1.2.0). Are you sure you ran all migrations on the database, i.e. `python ./manage.py migrate`?

**Comment by tximpa91** [comment]
Yes i ran the run migrate but it doesnt create acces token with that field

**Comment by tximpa91** [comment]
This happen when i make an update from 1.0.0 to 1.2.0 i make a clean install and make a migrate and all good but now i swap the model when i make a post for token it show me an error that violates foreign key constraint (app_id) of oauth2 provider application like is not swapping the model, after i delete the original oauth2 provider application it all works okey.

Can you anyone tell me what i did wrong, i put OAUTH2_PROVIDER_APPLICATION_MODEL in settings py after the migrate of the custom model, this thing not happen in 1.0.0

**Comment by jdelic** [comment]
> This happen when i make an update from 1.0.0 to 1.2.0 i make a clean install and make a migrate and all good

Hmm... what is the output of `manage.py showmigrations`?

I would assume that the field `source_refresh_token_id` doesn't get created because of the references to your own application model "being whack" (that's a technical term) and subsequent migrations failing.

> Can you anyone tell me what i did wrong, i put OAUTH2_PROVIDER_APPLICATION_MODEL in settings py after the migrate of the custom model, this thing not happen in 1.0.0

It took me quite a bit of research to figure out how to introduce swappable models into my own application's migrations so they work correctly. I use a custom Application model myself in my [authserver application](https://github.com/jdelic/authserver/) and perhaps it would help you to look at my setup:

  * This is where I [configure my custom Application model](https://github.com/jdelic/authserver/blob/develop/authserver/authserver/settings.py#L135)
  * Here is my [custom Application model](https://github.com/jdelic/authserver/blob/424fdf340188df14b1d5f0eeadf9f3108b1c9be4/authserver/mailauth/models.py#L371-L390)
  * and here is how I figured out to make sure that my [own Application model exists, i.e. my own initial migration runs before the oauth2_provider migration runs which introduces the foreign key to the application model](https://github.com/jdelic/authserver/blob/424fdf340188df14b1d5f0eeadf9f3108b1c9be4/authserver/mailauth/migrations/0001_initial.py#L22-L24). This runs migrations in the right order so the `oauth2_provider.models.Application` never gets created in the database and all foreign keys point to my own model instead.

Perhaps it'll help with your problem to modify your own setup similar to mine.
