### ISSUE TITLE
Provide _create_refresh_token method in oauth2_validators

### ISSUE THREAD

**Issue by thedustyrover** [jazzband/django-oauth-toolkit#652]
A handy overrideable method is provided for creating access tokens in the OAuth2Validator:

https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/oauth2_validators.py#L543

However there is no equivalent hook for creating refresh tokens, which is just a part of the save_bearer_token method:

https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/oauth2_validators.py#L523

Such a method is handy to override the default way that Tokens are constructed. E.g. in my case the User model does not exist in the same database as the Token, breaking the foreign-key constraint and making it impossible to actually create a RefreshToken with an attached user.

**Comment by n2ygk** [comment]
It seems to me that methods named starting with `_` are considered private and shouldn't generally be overridden as they aren't guaranteed to retain the same API. See https://www.python.org/dev/peps/pep-0008/ "Public attributes should have no leading underscores."

So if this is a generally useful feature, perhaps submit a PR that makes these methods "public".

**Comment by IvanAnishchuk** [comment]
I'd also change the return value of `save_bearer_token`. Currently it doesn't return anything but it would be useful if it returned the created access token and (if present) refresh token instead. Right now, if any post-creation token logic is needed in subclass it requires either extra database query or some other magic because created instances are lost. Like a simple `return access_token, refresh_token` in the end would be nice.

**Comment by IvanAnishchuk** [comment]
But either way, this issue seems to be resolved by #695 -- reopen if not.
