### ISSUE TITLE
SessionAuthenticationMiddleware removed from django v2.0 onwards.

### ISSUE THREAD

**Issue by vishal-pandey** [jazzband/django-oauth-toolkit#684]
Django.contrib.auth.middleware.SessionAuthenticationMiddleware is removed from django 2.0 onwards

It is still mentioned in the documentation [https://django-oauth-toolkit.readthedocs.io/en/latest/tutorial/tutorial_03.html#setup-a-provider](https://django-oauth-toolkit.readthedocs.io/en/latest/tutorial/tutorial_03.html#setup-a-provider)
Is there any work around of this

**Comment by ghedsouza** [comment]
@vishal-pandey If you look at the release notes for Django 2.0 (https://docs.djangoproject.com/en/3.0/releases/2.0/#miscellaneous), they say there's no need for this middleware anymore because the functionality it provided is enabled by default now.

So it should be safe to just remove from your list of middlewares.
