### ISSUE TITLE
unsupported_grant_type when verifying token at introspection endpoint

### ISSUE THREAD

**Issue by mhyousefi** [jazzband/django-oauth-toolkit#738]
Hi there.

In my **authorization server**, I have registered my **resource server** with the following specs:
- `Client-type`: `confidential` 
- `Authorization grant type`: `Resource owner password-based`

The way I look at this, the JS client will carry out the first step once (as sort of like a login process) to acquire an `access_token`. And then, every time it needs to use an API, it has to provide the `access_token` to the **API server (resource server)**. Then, the resource server sends a POST request to the authorization server to verify the `access_token` before it starts to process the JS client request.

1. I send the following POST request:
```curl -X POST -d "grant_type=password&username=<USER>&password=<PASS>&scope=<SCOPE>" -u"<CLIENT_ID>:<CLIENT_SECRET>" http://localhost:8000/o/token/```  
This works fine and I get an `access_token`.

2. I try this POST request to verify that the token is valid:
```curl -X POST -d "token=<ACCESS_TOKEN>" http://localhost:8000/o/token/```
This is when I get `{"error": "unsupported_grant_type"}`.

Is there something wrong with my request structure or am I wrong with the overall process?

**Comment by JonathanHuot** [comment]
Hi, it seems you have setup `/token` as your **Token Endpoint**, and you are reusing it thinking it is the **Introspect Endpoint**.

You must define two different URLs to have this working.

**Comment by mhyousefi** [comment]
Oh, I see!
Does this framework provide a url with pre-existing code to handle the *introspection endpoint* functionality? Or do I have to define a manual url in my Django authorization server to handle this. Could you provide some assistance?

**Comment by mhyousefi** [comment]
Also, is the process I mentioned the right way to approach Oauth2?

**Comment by JonathanHuot** [comment]
Hi @mhyousefi,
All flows in OAuth2 can be implemented but it really depends of your application architecture and the different components that you have.

Most of the time the ROPC grant should not be used and they confuse people because it is the only grant where we have "username" and "password" in it. Authorization Code grant must be used in almost every scenario.

I don't know much about your infrastructure, but this recommendation should be useful for most of the people:
- Define DjangoOauthToolkit as your IdentityProvider and your AuthorizationServer:
-- define /authorize, /token and /introspect endpoints; and allow your clients to use only authorization code grant
-- implement your js login screen in /authorize
-- see https://django-oauth-toolkit.readthedocs.io/en/latest/resource_server.html#setup-the-authentication-server
- Create any other ResourceServers (APIs)
-- follow https://django-oauth-toolkit.readthedocs.io/en/latest/resource_server.html by calling introspection requests

If you want to have all-in-one because you don't have separated API, you can skip the introspection because the API become the same server as the AuthorizationServer.

Also, I'd recommend following the tutorials there: https://django-oauth-toolkit.readthedocs.io/en/latest/tutorial/tutorial.html

Cheers

**Comment by mhyousefi** [comment]
Thank you for your thorough explanation! I was able to pull off the introspect part.

Regarding the grant type, ROPB seems to be a suitable choice when the client is trusted by the resource (API) server. Now, I am developing a Django API back-end for a mobile app and a web app (also developed & maintained by myself). Is this an example of when the client is NOT an outsider to the resource server? In other words, it doesn't seem hazardous to provide user credentials directly to the client app since they are both part of the same system.
