### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by dulmandakh** [jazzband/django-oauth-toolkit#832]
@auvipy could you please release new version with recent changes

**Comment by auvipy** [comment]
@n2ygk

**Comment by n2ygk** [comment]
@auvipy @dulmandakh We just issued a release a short time ago. People who want to use interim functionality can use `pip install git+https://github.com/jazzband/django-oauth-toolkit.git@<commit>`

@auvipy I haven't been paying close attention. Are the new commits bug fixes or new functionality? I don't see any changes in the CHANGELOG.

**Comment by n2ygk** [comment]
@dulmandakh Thanks for all your PRs!

Please submit a PR that updates CHANGELOG to show the relevant changes such as requirement for oauthlib>=3.1.0. (See example from prior releases). Something like this would be great:
```
## [1.3.3] unreleased
### Changed
* Change requirement for oauthlib>=3.1.0
```
In hindsight, this would have been something to come in with #825.
Also, please add your name to AUTHORS and simply check the box for each future PR.

Otherwise it doesn't make sense for users of this package to see a new release show up at pypi that doesn't document anything having changed.

Thanks!

**Comment by MattBlack85** [comment]
closing this, stau tuned on #878
