### ISSUE TITLE
How read the docs is updated?

### ISSUE THREAD

**Issue by wiliamsouza** [jazzband/django-oauth-toolkit#842]
After the merge https://github.com/jazzband/django-oauth-toolkit/pull/841 nothing magically happened it sens to be a manual step who knows it or can help with it?

**Comment by n2ygk** [comment]
It's there now: https://django-oauth-toolkit.readthedocs.io/en/latest/getting_started.html

I don't recall exactly how/when this gets triggered. I think I've been doing it manually because we had some issues and recently converted from travis to github actions. We may still need to add an action to rebuild the docs.

@MattBlack85 do you know what we need to do here?
